enum EClasses {
    WARRIOR = "WARRIOR",
    RANGER = "RANGER",
    SORCERESS = "SORCERESS",
    BERSERKER = "BERSERKER",
    TAMER = "TAMER",
    VALKYRIE = "VALKYRIE",
    WIZARD = "WIZARD",
    WITCH = "WITCH",
    MUSA = "MUSA",
    MAEHWA = "MAEHWA",
    NINJA = "NINJA",
    KUNOICHI = "KUNOICHI",
    DARK_KNIGHT = "DARK_KNIGHT",
    STRIKER = "STRIKER",
    MYSTIC = "MYSTIC",
    LAHN = "LAHN",
    ARCHER = "ARCHER",
    SHAI = "SHAI",
    GUARDIAN = "GUARDIAN"
}

export default EClasses;