enum EMethod {
    UPDATE_THEME = "UPDATE_THEME",

    INSERT_CHARACTER = "INSERT_CHARACTER",
    UPDATE_CHARACTER = "UPDATE_CHARACTER",

    INSERT_HORSE = "INSERT_HORSE",
    UPDATE_HORSE = "UPDATE_HORSE"
}

export default EMethod;