enum EMethod {
    UPDATE_PROFILE = "UPDATE_PROFILE",
    UPDATE_SETTING = "UPDATE_SETTING",

    GET_CHARACTER = "GET_CHARACTER",
    INSERT_CHARACTER = "INSERT_CHARACTER",
    UPDATE_CHARACTER = "UPDATE_CHARACTER",
    REMOVE_CHARACTER = "REMOVE_CHARACTER",

    GET_HORSE = "GET_HORSE",
    INSERT_HORSE = "INSERT_HORSE",
    UPDATE_HORSE = "UPDATE_HORSE",
    REMOVE_HORSE = "REMOVE_HORSE",

    GET_USER_SERVICE = "GET_USER_SERVICE",
    CHECK_USER_NAME = "CHECK_USER_NAME",
    INSERT_USER_PASSWORD = "INSERT_USER_PASSWORD",
    UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD"
}

export default EMethod;