enum EMethod {
    UPDATE_PROFILE = "UPDATE_PROFILE",
    UPDATE_SETTING = "UPDATE_SETTING",

    GET_CHARACTER = "GET_CHARACTER",
    SAVE_CHARACTER = "SAVE_CHARACTER",
    REMOVE_CHARACTER = "REMOVE_CHARACTER",

    GET_HORSE = "GET_HORSE",
    INSERT_HORSE = "INSERT_HORSE",
    UPDATE_HORSE = "UPDATE_HORSE",
    REMOVE_HORSE = "REMOVE_HORSE",

    REFRESH_USERNAME = "REFRESH_USERNAME"
}

export default EMethod;